#!/bin/bash
# Testing Guide for Pitch Shifter Fixes

echo "=== Pitch Shifter Testing Guide ==="
echo ""
echo "To run the application and test both fixes:"
echo ""
echo "1. Set up the environment:"
echo "   python -m venv .venv"
echo "   source .venv/bin/activate"
echo "   pip install -r requirements.txt"
echo ""
echo "2. Start the backend server:"
echo "   uvicorn pitch_shifter_backend.main:app --reload --app-dir src"
echo ""
echo "3. Open the frontend:"
echo "   Navigate to http://127.0.0.1:8000/ in your browser"
echo ""
echo "=== Test Case 1: YouTube Download ==="
echo "- Click on 'YouTube URL' tab"
echo "- Paste a short YouTube video URL:"
echo "  Example: https://www.youtube.com/watch?v=dQw4w9WgXcQ"
echo "- Set semitone shift (e.g., 0, or any value from -12 to +12)"
echo "- Click 'Fetch & process'"
echo "- Watch the status update: queued → running → completed"
echo "- Once completed, the VIDEO player should auto-load"
echo "- Click Play to stream the processed video in browser"
echo ""
echo "=== Test Case 2: Audio File Upload ==="
echo "- Click on 'Upload a file' tab"
echo "- Select an MP3 or WAV file from your computer"
echo "- Set a semitone shift (e.g., -5 or +5)"
echo "- Click 'Upload & process'"
echo "- Once completed, the AUDIO player should auto-load"
echo "- Click Play to stream the processed audio in browser"
echo ""
echo "=== Test Case 3: Video File Upload ==="
echo "- Click on 'Upload a file' tab"
echo "- Select an MP4 or WebM video from your computer"
echo "- Set a semitone shift"
echo "- Click 'Upload & process'"
echo "- Once completed, the VIDEO player should auto-load"
echo "- Click Play to stream the processed video in browser"
echo ""
echo "=== Expected Behavior After Fixes ==="
echo "✓ YouTube downloads complete without errors"
echo "✓ Processed media automatically loads in the correct player"
echo "✓ Placeholder text is hidden when player is loaded"
echo "✓ Both audio and video playback work immediately"
echo "✓ No need to manually download files"
echo ""
echo "=== Debugging if Needed ==="
echo "- Check browser console for any JavaScript errors (F12)"
echo "- Check backend server logs for any Python errors"
echo "- Verify jobs directory has input files in data/jobs/{job_id}/input/"
echo "- Verify output files exist in data/jobs/{job_id}/output/"
echo ""
