apiVersion: apps/v1
kind: Deployment
metadata:
  name: pitch-shifter-backend
  namespace: pitch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pitch-shifter-backend
  template:
    metadata:
      labels:
        app: pitch-shifter-backend
    spec:
      containers:
        - name: api
          image: elroymalayov/pitch-shifter-backend:1.9
          imagePullPolicy: Always
          command: ["python", "-m", "uvicorn"]
          args:
            - "pitch_shifter_backend.main:app"
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "8000"
            - "--app-dir"
            - "/app/src"
          ports:
            - containerPort: 8000
          env:
            - name: PITCH_ENVIRONMENT
              value: production
            - name: PITCH_DATA_DIR
              value: /app/data
            - name: PITCH_UPLOADS_DIR
              value: /app/data/uploads
            - name: PITCH_OUTPUTS_DIR
              value: /app/data/outputs
            - name: PITCH_JOBS_DIR
              value: /app/data/jobs
            - name: PYTHONPATH
              value: /app/src
            - name: PITCH_YOUTUBE_COOKIES_FILE
              value: /app/config/cookies.txt
          volumeMounts:
            - name: media-data
              mountPath: /app/data
            - name: cookies
              mountPath: /app/config/cookies.txt
              subPath: cookies.txt
      volumes:
        - name: media-data
          persistentVolumeClaim:
            claimName: pitch-shifter-data
        - name: cookies
          secret:
            secretName: youtube-cookies
