apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pitch-shifter-backend
  namespace: pitch
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "500m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - pitch.elroy.site
      secretName: pitch-shifter-tls
  rules:
    - host: pitch.elroy.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pitch-shifter-backend
                port:
                  number: 80
